spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8005
mybatis:
  type-aliases-package: com.hzit.api.bean
  mapper-locations:
  - classpath:mapper/**/*.xml
spring:
  profiles: dev
  application:
    name: springcloud-dept  # 应用的名称   多实例 名称必须保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/rbac
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka # eureka服务器的地址   单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance: 
    instance-id: springcloud-dept:8005  #设置访问的别名
    prefer-ip-address: true        #显示ip地址
info:                              #点击别名  访问info信息
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---
server:
  port: 8006
mybatis:
  type-aliases-package: com.hzit.api.bean
  mapper-locations:
  - classpath:mapper/**/*.xml
spring:
  profiles: test
  application:
    name: springcloud-dept  # 应用的名称   多实例 名称必须保持一致
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/rbac
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      
# 配置服务注册信息      
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7003/eureka # eureka服务器的地址   单机版
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版
  instance: 
    instance-id: springcloud-dept:8006  #设置访问的别名
    prefer-ip-address: true        #显示ip地址
info:                              #点击别名  访问info信息
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}