spring: 
    profiles: 
        active: 
           - dev
---
spring: 
    profiles: dev
    application: 
        name: springcloud-eureka-client-dev
server: 
  port: 7002
eureka: 
  instance: 
    hostname: localhost  #指定主机  本地的域名映射
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #设置eureka server的交互地址，即对外暴露的地址
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/  #其他两个服务端的地址
---
spring: 
    profiles: test
    application: 
        name: springcloud-eureka-client-test
server: 
  port: 7003
eureka: 
  instance: 
    hostname: localhost  #指定主机  本地的域名映射
  client: 
    register-with-eureka: false     #false表示不向注册中心注册自己
    fetch-registry: false           #false表示自己就是注册中心，职责是维护实例，不参加检索
    service-url: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    #设置eureka server的交互地址，即对外暴露的地址